#----------------------------------------------------------------------------------------------------------------------------------------------------------------
# Spring Default Setup
#----------------------------------------------------------------------------------------------------------------------------------------------------------------
# name : project name
# rabbitmq : rabbitMq Setup
# jps : jpa setup
#
spring:
  rabbitmq:
    host: ${RABBITMQ_SERVER_URL:coe-helm-rabbitmq}
    port: ${RABBITMQ_SERVER_PORT:5672}
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true
  datasource:
    sql-script-encoding: UTF-8
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://coe-helm-mariadb:3306/coe
#    url: jdbc:mariadb://localhost:3306/coe
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}

#----------------------------------------------------------------------------------------------------------------------------------------------------------------
# Endpoint output options for Hystrix Stream
#----------------------------------------------------------------------------------------------------------------------------------------------------------------
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"

springfox:
  documentation:
    swagger:
      v2:
        path: /api/v1/customers/api-docs


